### PR TITLE
Content manager document API - GET call

### PR DESCRIPTION
**Pull request by Petros1**

### CODE REVIEW

**Review by mesayas — COMMENTED** [review]
1.  you are trying to do multiple db calls in a loop, its a no Go, plz use table join, 
examples are  
https://arjunamrutiya.medium.com/mastering-laravel-join-queries-a-step-by-step-guide-4f122f487253  and  
https://www.educative.io/answers/how-to-perform-inner-join-of-two-tables-in-laravel-query  

2. don't hard code the offset, check if limit and offset exists in request param separately, if exists use them if not use limit=10 and offset=0

**Comment by Petros1** [comment]
@mesayas, I have added few changes based on your comments. Please review, thanks!

**Review by misghna — COMMENTED** [review]
The GE looks good thanks buddy! But I was hopping we merge all the crud operations together as one user story. Plz add those ops and let me know!

**Comment by Petros1** [comment]
hey @mesayas I completed all calls, please review. thanks!

**Pull request merged**
